services:
  db:
    build:
      context: ./DB
      dockerfile: Dockerfile
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: colocolo # Contraseña posibilemente modificable en un futuro: utilizandola a través de .env y no directamente hardcodeada en dockercompose
      POSTGRES_DB: db
    ports:
      - "5432:5432"
  
  bus:
    image: jrgiadach/soabus:v1
    container_name: bus
    restart: unless-stopped
    ports:
      - "5000:5000"
  
  usuario:
    image: python:3.10-slim
    container_name: servicio_usuario
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASS=colocolo
      - DB_NAME=db
    volumes: 
      - ./Usuarios:/app
    working_dir: /app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python usuarios.py"
    depends_on:
      - bus
      - db
      
  cliente:
    image: python:3.10-slim
    container_name: servicio_cliente
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASS=colocolo
      - DB_NAME=db
    volumes: 
      - ./Clientes:/app
    working_dir: /app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python clientes.py"
    depends_on:
      - bus
      - db
  
  productos:
    image: python:3.10-slim
    container_name: servicio_producto
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASS=colocolo
      - DB_NAME=db
    volumes: 
      - ./Productos:/app
    working_dir: /app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python productos.py"
    depends_on:
      - bus
      - db

  manejo_de_datos:
    image: python:3.10-slim
    container_name: servicio_manejo_de_datos
    restart: unless-stopped
    environment: 
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASS=colocolo
      - DB_NAME=db
    volumes:
      - ./Manejo_de_Datos:/app
    working_dir: /app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python manejo.py"
    depends_on:
      - bus
      - db
  
  analisis:
    image: python:3.10-slim
    container_name: servicio_analisis
    restart: unless-stopped
    environment: 
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASS=colocolo
      - DB_NAME=db
    volumes:
      - ./Analisis:/app
    working_dir: /app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python analisis.py"
    depends_on:
      - bus
      - db

  frontend:
      build:
        context: ./FrontEnd # Asegúrate de que esta sea la ruta a tu carpeta del front
        dockerfile: Dockerfile
      container_name: aplicacion_frontend
      restart: unless-stopped
      ports:
        - "8000:8000"
      depends_on:
        - bus
        - db